### ISSUE TITLE
How to use this app

### ISSUE THREAD

**Issue by dennrich** [pharada/ipaghazi#1]
Hi,
I'm very interested in using this ota platform to simply distribute in-house apps internally for testing.

I ran the container but don't understand how to actually link the IPA files.

This is how I run the container:

```
version: "3.4"

services:
    db:
        image: mongo:3
        container_name: ipaota-db
        restart: always
        volumes:
            - db:/data/db

    platform:
        image: pharada/ipaghazi
        container_name: ipaota-platform
        restart: always
        #depends_on: db
        ports:
            - "8090:80"
        volumes:
            - data:/data
        environment:
            - IPAGHAZI_PORT=80
            - IPAGHAZI_BASEURL=http://<THESERVER>:8090
            - IPAGHAZI_MONGODB=mongodb://ipaota-db/ipaghazi
            - IPAGHAZI_ANON_PERMS=browse-app
            - IPAGHAZI_ROOT_USER=admin
            - IPAGHAZI_ROOT_KEY=<THEKEY>
            - IPAGHAZI_METHODS=url

volumes:
    data:
    db:
```

Now I understand that I need to pass ```method-params``` to ipaghazi but don't know how. I experimented with several url patterns but nothing works.

Could you please explain this more deeply in the README?

Many thanks in advance and regs
Dennis
